[package]
name = "fortun-driver-install"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fortun-cli = { path = "../ForTunCli"}
rust-embed="8.0.0"
tracing = "0.1"
tracing-subscriber = "0.3"